### ISSUE TITLE
TabModule is not an NgModule, getting error while adding to angular 4 App.

### ISSUE THREAD

**Issue by siva563** [karanhudia/angular-tabs-component#1] opened 2017-09-11 06:36 UTC
Hi @karanhudia , I am trying to add to my Angular 4 application, while building the application i am getting above error, could you please help me out. Thanks in advance !!!

**Comment by anilongit** [comment] 2017-10-23 14:42
Did you find a fix for this?  Thanks

**Comment by karanhudia** [comment] 2017-10-24 11:11
I have fixed this issue in the latest published version @1.0.4
Please check if its working for you and update me so that i can close the issue.

**Comment by anilongit** [comment] 2017-10-24 14:17
Thanks for addressing!
Fixed most issues in web pack.  Only one issue left is (when publishing) thrown by '@ngtools/webpack' :
        module: {
            rules: [
                { test: /\.ts$/, include: /ClientApp/, use: isDevBuild ? ['awesome-typescript-loader?silent=true', 'angular2-template-loader'] : '@ngtools/webpack' },

    ERROR in ./$$_gendir/~/angular-tabs-component/dist/containers/tabs-container/tabs.container.ngfactory.ts
    Module parse failed: C:\ws\Cyberian\DEVELOPMENT\Source\Cyberian\$$_gendir\node_modules\angular-tabs-component\dist\containers\tabs-container\tabs.container.ngfactory.ts Unexpected token (12:26)
    You may need an appropriate loader to handle this file type.
    | import * as i1 from '@angular/common';
    | import * as i2 from 'angular-tabs-component/dist/containers/tabs-container/tabs.container';
    | const styles_TabsContainer:any[] = ['*[_ngcontent-%COMP%]{margin:0px;padding:0px}[_nghost-%COMP%]{padding:10px 10px;display:flex;flex-direction:column;position:relative;min-height:calc(100vh - 20px)}.tabs__tab-bar[_ngcontent-%COMP%]{align-self:center;border-radius:4px;overflow:hidden;margin-bottom:-12px;z-index:1000;border:1px solid #c9c9c9}.tabs__tab[_ngcontent-%COMP%]{padding:4px 10px;display:inline-block;background-color:white;cursor:pointer}.tabs__tab.active[_ngcontent-%COMP%]{background-color:#6fbbff !important;color:white}.overlay[_ngcontent-%COMP%]{background:#e0e0e0;opacity:0.5;bottom:0;left:0;position:absolute;right:0;top:0;z-index:1000}'];
    | export const RenderType_TabsContainer:i0.RendererType2 = i0.╔╡crt({encapsulation:0,
    |     styles:styles_TabsContainer,data:{}});
     @ ./$$_gendir/ClientApp/app/components/companySearch/companySearch.component.ngfactory.ts 15:0-139
     @ ./$$_gendir/ClientApp/app/components/app/app.component.ngfactory.ts
     @ ./$$_gendir/ClientApp/app/app.module.browser.ngfactory.ts
     @ ./ClientApp/boot.browser.ts

**Comment by anilongit** [comment] 2017-10-24 14:19
*thrown by @ngtools/webpack
module: {
 rules: [
 { test: /.ts$/, include: /ClientApp/, use: isDevBuild ? ['awesome-typescript-loader?silent=true', 'angular2-template-loader'] : @ngtools/webpack },

**Comment by anilongit** [comment] 2017-10-24 14:20
Can't seem to write this so separated with a plus: @ + ngtools/webpack

**Comment by karanhudia** [comment] 2017-10-25 06:11
Can you reproduce the error in a plunkr or somewhere else ?

**Comment by anilongit** [comment] 2017-10-25 10:27
I have had to roll back to 1.0.3 as on page load I was getting (1.0.5) "ERROR Error: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'true'. Current value: 'false'."

**Comment by karanhudia** [comment] 2017-10-26 06:56
I have fixed the "ExpressionChangedAfterItHasBeenCheckedError" error in the latest version. Verify if its working for you.

**Comment by karanhudia** [comment] 2018-09-04 16:24
Closing this issue, since it has not been reproduced or reported since then.

**Closed as completed by karanhudia** 2018-09-04 16:24 UTC
